#### getting photo's metadata
GET http://localhost:3000/api/filters/metadata/1 HTTP/1.1

#### applying filter patch
PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Type: application/json

{
  "filterType": "rotate",
  "id": 1,
  "rotateValue": 180
}

#### applying filter patch
PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Type: application/json

{
  "filterType": "resize",
  "id": 1,
  "heightValue": 180,
  "widthValue": 180
}

#### applying filter patch
PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Type: application/json

{
  "filterType": "negate",
  "id": 1
}

#### applying filter patch
PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Type: application/json

{
  "filterType": "crop",
  "id": 1,
  "heightValue": 10,
  "widthValue": 10,
  "topValue": 10,
  "leftValue": 10
}



